apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::624676567225:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1MFJXTFZUY4YO
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::624676567225:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::624676567225:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-O0BG18MDIWGI\n  username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n  rolearn: arn:aws:iam::\u003c624676567225\u003e:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-08-18T17:37:33Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1805","uid":"6dbd2a7a-7462-49a4-9032-0e33875eb426"}}
  creationTimestamp: "2023-08-18T17:37:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8757"
  uid: 6dbd2a7a-7462-49a4-9032-0e33875eb426