apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::205656647128:roleeksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1B2S9GILQN19J
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::205656647128:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-08T17:07:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3062"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 855521bb-de98-4289-810f-4b368402bab2