apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::205656647128:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-IRJBITJ9PK1Q
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-18T17:37:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1182"
  uid: 6dbd2a7a-7462-49a4-9032-0e33875eb426
