apiVersion: v1
kind: ConfigMap
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::519002666132:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DBHED9TMYRZZ
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::519002666132:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::205656647128:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DBHED9TMYRZZ\n  username: system:node:{{EC2PrivateDNSName}}\n  - system:masters\n  rolearn: arn:aws:iam::205656647128:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2022-05-11T11:16:26Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1631","uid":"86402a4e-a9ff-4721-8c24-f0c4258f7440"}}
  creationTimestamp: "2023-08-11T15:53:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "15257"
  uid: 0e572a5d-17fb-4955-bb17-892a5f342db5
